//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/AssetsMathieu/script/CLic.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CLic: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CLic()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CLic"",
    ""maps"": [
        {
            ""name"": ""clic"",
            ""id"": ""5b8da747-0809-4523-ba96-7d1be29afc3e"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""7f1d9e40-545f-432a-a447-c72a8b3a87df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0104824f-7f4f-4ab7-9ea3-701b7d20729d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // clic
        m_clic = asset.FindActionMap("clic", throwIfNotFound: true);
        m_clic_Newaction = m_clic.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // clic
    private readonly InputActionMap m_clic;
    private List<IClicActions> m_ClicActionsCallbackInterfaces = new List<IClicActions>();
    private readonly InputAction m_clic_Newaction;
    public struct ClicActions
    {
        private @CLic m_Wrapper;
        public ClicActions(@CLic wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_clic_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_clic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ClicActions set) { return set.Get(); }
        public void AddCallbacks(IClicActions instance)
        {
            if (instance == null || m_Wrapper.m_ClicActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ClicActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IClicActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IClicActions instance)
        {
            if (m_Wrapper.m_ClicActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IClicActions instance)
        {
            foreach (var item in m_Wrapper.m_ClicActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ClicActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ClicActions @clic => new ClicActions(this);
    public interface IClicActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
